# Generated by Django 4.0.4 on 2022-05-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casemailinglist',
            table='case_mailing_list',
        ),
        migrations.AlterModelTable(
            name='commonmailinglist',
            table='common_mailing_list',
        ),
    ]
